runtime: java17
entrypoint: java -jar target/backend_api-1.0-SNAPSHOT-jar-with-dependencies.jar

automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    script: this field is required, but ignored
